// <auto-generated />
namespace LapTrinhQuanLy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_table_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202110010615344_create_table_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
